### ISSUE TITLE
Issueベース開発レビュー用のIssueを作成

### ISSUE THREAD

**Issue by yuki0877** [yuki0877/Clock-Safety#10]
■Webアプリの概要
Googleスマートウォッチから得られる健康管理データを使用して、離れて暮らす高齢家族が健康な状態で暮らしているのかを確認できるサービスです。  
スマートウォッチを付けて生活をしてもらい、webアプリ上で離れて暮らす高齢家族の日々の健康状態を確認することができます。  

■ProjectsのURL

■MVPリリースまで
- [ ] rails new
- [ ] デプロイ
- [ ] トップページ
- [ ] ログイン機能（OAuthログイン）
- [ ] 健康データ表示機能（心拍数、睡眠時間等）
- [ ] 異常値検知（心拍数）

■MVP後
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] RSpec
- [ ] グラフ表示機能（健康データの時系列変動）
- [ ] 通知機能（メール）
- [ ] 活動ログ表示機能（運動量、歩数）  

■MVPレビュー依頼予定日
予定日：2024年 9月 10日

**Comment by Tsuchiya2** [comment]
<img width="757" alt="image" src="https://github.com/user-attachments/assets/59ef0e54-b246-4816-9e93-e3cafe82587f">


対応ありがとうございます。
Projectsページにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。
カリキュラムをご確認いただいて、レビューワー側で上記が確認できるように対応いただき、再提出操作をお願いいたします。

**Comment by yuki0877** [comment]
レビューありがとうございます。
間違っており、プロジェクトにあがっていませんでした。すみません。
お手数ですが、再レビューお願いします。

**Comment by kashiwagi-rena** [comment]
ご提出ありがとうございます。
以下、コメントです。

---

https://www.figma.com/design/UMn6QEW28fiYXKHVa8SbMi/Untitled?node-id=0-1&t=Kz6jGcvJ9yyZ5aI3-0

上記、カリキュラムのURLです。適宜確認してくださると幸いです。

1.  view画面に関してのIssueが存在しておりません。作成漏れや時間配分の観点から画面遷移図にある画面のIssueの作成をおすすめいたします。(上記カリキュラムにも「トップページの作成」のIssueがありますので、再度確認してくださると想像がつきやすいかと思います)

2. > ストーリーポイントには、通常1〜13までのフィボナッチ数が使われますが、実装方法が見えていない13や実装難易度が高い状態の8, 5の数字は使用しないことをお勧めします。もし5以上のタスクになりそうであれば、タスクを細分化して最大でも3以下になるように設定してください。

ストーリーポイント5のものがありますので、こちらを細分化していただきたいです。おすすめのやり方としては、調べるタスクと実装タスクに分けて、ストーリーポイント3にしてみてください。一旦調べることに集中していただいて、実装の道筋を確認していただいてから実装する方が不透明箇所・明確箇所の可視化をすることができ、実装も進めやすいと認識しています。実装を行う前に不透明箇所がわかることで、技術面談等を使用していただき、相談しながらの実装をすることも可能と認識しております。また、Issue一つへのハードルが下がり、進歩を感じなから無理なく実装可能と認識しての提案です。

**Comment by yuki0877** [comment]
レビューありがとうございます。
丁寧に教えていただきありがとうございます。
view画面のissueの追加・タスクの細分化をしました。
お手数ですが、再度レビューお願いします。

**Comment by TakenakaEri** [comment]
ありがとうございます。おおむね良いかと思いますので、LGTMです！

ただ、それぞれのissueに対してもう少し細かく定義してタスクを設定できるよ良いなと感じました。（具体的には”異常値検知ロジックの設計”や”HealthDataモデルへのメソッド追加と動作確認”の項目などの内容が曖昧だと感じました）

既に頭の中で設計がある場合は、issueに落とし込んでから次に進んでください。
技術検証やロジックは後で考えるとなると面倒なことになる可能性が高いので、先にやっておくとスムーズに進むと思います。
（必要であれば、適時issueのタスクは増やしてください）

**Comment by yuki0877** [comment]
レビュー・LGTMありがとうございます。
もっと具体的になるように、適宜issueを変更したり、増やしていきたいと思います。
