### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by yuki0877** [yuki0877/Clock-Safety#24]
## 各種情報
サービス名 Clock Safety
サービスURL. https://clock-safety-front.vercel.app/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] ログイン機能（OAuthログイン）　※Googleアカウントに対応済み
- [ ] 健康データ表示機能（心拍数、睡眠時間等）　※FitbitAPIを使用して、心拍数・睡眠時間データの表示に対応済み。
- [ ] 異常値検知（心拍数） ※FitbitAPIを使用してwebアプリで祖母の健康管理データを見ることが出来る。　※高心拍数・低心拍数の異常値検知データの表示に対応。

## READMEレビュー時から変更した機能
レビューのお願いとログイン情報について
この度は、レビューにご協力いただきありがとうございます。

現在、ゲストログイン機能の実装が完了していないため、お手数ですが、下記のアカウント情報でログインしていただくようお願いいたします。

ログイン情報
メールアドレス：akemi.sample.1203@gmail.com
パスワード：akemi12033536

ログイン手順
以下のURLにアクセスしてください。 URL：https://clock-safety-front.vercel.app/
「サインイン」ボタンをクリックし、Googleアカウントでログインしてください。
ログイン後、Fitbitの認可画面に遷移しますので、続けてGoogleアカウントで認証してください。
認証が完了すると、本アプリ（Clock Safety）の健康データ表示ページにアクセスできます。

ご不便をおかけして申し訳ございません
ゲストログイン機能は、本リリースまでに実装予定です。ご不便をおかけしますが、何卒よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
ログインできないため挙動の確認ができませんでした。ご確認＆ご対応をお願いいたします。

![image](https://github.com/user-attachments/assets/cc0523f8-3a11-4afd-9288-fae631194be2)


![image](https://github.com/user-attachments/assets/2f03f7df-a8f8-439f-9346-89c34b060b78)

**Comment by yuki0877** [comment]
レビューありがとうございます。
お手数おかけしてすみません。
二段階認証のプロセスはオフにしたのですが、住んでいる地域が違うため不審なアクセスと判断され本人確認を求められる可能性があるようです。その際は本人確認を行うため、お手数ですが時間が空いた時に再レビューお願いします。

**Comment by shota-hope** [comment]
以下のようになりログインができませんでした。
[![Image from Gyazo](https://i.gyazo.com/a7d7333531c04f0a643b7c7145bb50cb.png)](https://gyazo.com/a7d7333531c04f0a643b7c7145bb50cb)

**Comment by yuki0877** [comment]
レビューありがとうございます。ログインできなかった件でお手数をおかけし、申し訳ありませんでした。セキュリティを下げるため、二段階認証をオフにして対応しましたが、住んでいる地域とは異なる場所からのログインが不正アクセスと判断され、ログインができない事態に陥ってしまいました。

どうすべきか悩んでいたところ、技術面談で冨田講師に相談した結果、講師専用のログインボタンを作成し、サンプルの健康データを表示できる形で対応することになりました。冨田講師には、技術面談の際に画面共有を通してGoogleログインし、Fitbitのデータが取得できることを確認していただいています。

お手数をおかけしますが、サンプルデータを入れたページを作成しましたので、再度レビューをお願いいたします。

【ログイン手順】
以下のURLにアクセスしてください。
URL：https://clock-safety-front.vercel.app/
アクセス後、「講師の方はこちら」というボタンからログインいただくと、健康データが表示されます。

また、実際にGoogleログインを使用してFitbitのデータを取得する様子を動画にしました。お時間があれば、ご確認いただけると幸いです。

Uploading 画面収録 2024-09-13 16.08.42 (video-converter.com).mov…

**Comment by yuki0877** [comment]
レビューありがとうございます。ログインできなかった件でお手数をおかけし、申し訳ありませんでした。セキュリティを下げるため、二段階認証をオフにして対応しましたが、住んでいる地域とは異なる場所からのログインが不正アクセスと判断され、ログインができない事態に陥ってしまいました。

どうすべきか悩んでいたところ、技術面談で冨田講師に相談した結果、講師専用のログインボタンを作成し、サンプルの健康データを表示できる形で対応することになりました。冨田講師には、技術面談の際に画面共有を通してGoogleログインし、Fitbitのデータが取得できることを確認していただいています。

お手数をおかけしますが、サンプルデータを入れたページを作成しましたので、再度レビューをお願いいたします。

【ログイン手順】
以下のURLにアクセスしてください。
URL：https://clock-safety-front.vercel.app/
アクセス後、「講師の方はこちら」というボタンからログインいただくと、健康データが表示されます。

また、実際にGoogleログインを使用してFitbitのデータを取得する様子を動画にしました。お時間があれば、ご確認いただけると幸いです。
https://github.com/user-attachments/assets/f924f71a-5716-41d7-8c93-0aeaf40a1d0d

**Comment by yuki0877** [comment]
レビューありがとうございます。ログインできなかった件でお手数をおかけし、申し訳ありませんでした。セキュリティを下げるため、二段階認証をオフにして対応しましたが、住んでいる地域とは異なる場所からのログインが不正アクセスと判断され、ログインができない事態に陥ってしまいました。

どうすべきか悩んでいたところ、技術面談で冨田講師に相談した結果、講師専用のログインボタンを作成し、サンプルの健康データを表示できる形で対応することになりました。冨田講師には、技術面談の際に画面共有を通してGoogleログインし、Fitbitのデータが取得できることを確認していただいています。

お手数をおかけしますが、サンプルデータを入れたページを作成しましたので、再度レビューをお願いいたします。

【ログイン手順】
以下のURLにアクセスしてください。
URL：https://clock-safety-front.vercel.app/
アクセス後、「講師の方はこちら」というボタンからログインいただくと、健康データが表示されます。

また、実際にGoogleログインを使用してFitbitのデータを取得する様子を動画にしました。お時間があれば、ご確認いただけると幸いです。
https://drive.google.com/file/d/1QKrymOBEFb1tMRWr1aKirIS2BdbMLiX7/view?usp=drive_link

**Comment by kashiwagi-rena** [comment]
ログイン対応ありがとうございまます。確認いたしました。

以下、私からの気になった点について記載させていただきます。
- 全てのページは確認取れなかったのですが、ヘッターが被ってしまうところがあるようです。本リリースまでに被らないようにしてください。


機能確認が取れました。**LGTM**です！
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下も取り組む =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。

**Comment by yuki0877** [comment]
LGTMありがとうございます。
本リリースに向けて頑張って行きます。
